### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [mhazhary/mhazhary.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by mhazhary** [comment]
I don't think this is worth to be included to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) since this is my personal ZSH theme and it only has one Distro icon (which is RHEL) for the sake of simplicity.

**Comment by unixorn** [comment]
Fair enough.
